// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKs0q4e52WAiQt_gGnAqSVTlBCB36dqy4',
    appId: '1:216110277304:web:5b28a565f04a5f332c0a4d',
    messagingSenderId: '216110277304',
    projectId: 'wastemgt-28654',
    authDomain: 'wastemgt-28654.firebaseapp.com',
    storageBucket: 'wastemgt-28654.firebasestorage.app',
    measurementId: 'G-PS5VE0FWLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOHpxnhTmBxyXCramgmlO-XO6ZUv24EHs',
    appId: '1:216110277304:android:ca31441bba14df072c0a4d',
    messagingSenderId: '216110277304',
    projectId: 'wastemgt-28654',
    storageBucket: 'wastemgt-28654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlOPPRdO0NPvEH41_Ykceh2Vzu0SmE5g',
    appId: '1:216110277304:ios:9f82843355efdf962c0a4d',
    messagingSenderId: '216110277304',
    projectId: 'wastemgt-28654',
    storageBucket: 'wastemgt-28654.firebasestorage.app',
    iosClientId: '216110277304-s235akhhprdgjif5n08al0miked2j5ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.waste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAlOPPRdO0NPvEH41_Ykceh2Vzu0SmE5g',
    appId: '1:216110277304:ios:9f82843355efdf962c0a4d',
    messagingSenderId: '216110277304',
    projectId: 'wastemgt-28654',
    storageBucket: 'wastemgt-28654.firebasestorage.app',
    iosClientId: '216110277304-s235akhhprdgjif5n08al0miked2j5ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.waste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKs0q4e52WAiQt_gGnAqSVTlBCB36dqy4',
    appId: '1:216110277304:web:e65d24ecf3fccd882c0a4d',
    messagingSenderId: '216110277304',
    projectId: 'wastemgt-28654',
    authDomain: 'wastemgt-28654.firebaseapp.com',
    storageBucket: 'wastemgt-28654.firebasestorage.app',
    measurementId: 'G-78F3M32X5X',
  );
}
